### ISSUE TITLE
Add parse-org* functions to use it as a library

### ISSUE THREAD

**Issue by schoettl** [200ok-ch/org-parser#19]
in `core.cljs`:
```
(defn parse-org [text] ...)   <- to parse a org string
(defn parse-org-file [path & args] ...)    <- to parse a file
```

See also this and next comment:
https://github.com/200ok-ch/org-parser/pull/18#issuecomment-640778504

**Comment by rollacaster** [comment]
Hi, are there any plans to publish org-parser as library?

As a workaround I created a [fork](https://github.com/rollacaster/org-parser) with a `deps.edn` file so I can [depend on it via git](https://clojure.org/guides/deps_and_cli#_using_git_libraries) (I'll use this [here](https://github.com/rollacaster/org-parser-tree/blob/main/deps.edn)). If that looks a like a good workaround to you until the library is officially published (at least I could not find it on Clojars) I am happy to open a PR for it.

**Comment by munen** [comment]
Hi @rollacaster 

Thanks for jumping in! 

> Hi, are there any plans to publish org-parser as library?

Yes, definitely!

org-parser started as a sister project to [organice](https://github.com/200ok-ch/organice/) (https://github.com/200ok-ch/org-parser#why-is-this-project-useful), so we are building org-parser with a pretty big use-case in mind that's already well used and tested.

While organice is written in JavaScript, with org-parser we explicitly went multi-platform, so that it can be used as widely as possible with parts of the EBNF code being completely platform-independent.

We haven't published org-parser as a library anywhere, yet, but your org-parser-tree project clearly shows that this is overdue!(;

If you can, I'd be happy for a PR with your changes - maybe even with a small documentation in the readme on how to use it using `deps.edn`. If you do have a snippet for auto-publication via CI to Clojars, that would also be great. Otherwise we will take care of that.

As a side-note: We are going to expand the `transform` namespace of org-parser further in order to get a data-structure that's more usable for consuming applications. There might be overlap with your org-parser-tree project - or even synergies to join into one project. @branch14 and I have already consulted on how to proceed in that regard and he's in the lead in that effort.

**Comment by rollacaster** [comment]
> If you can, I'd be happy for a PR with your changes - maybe even with a small documentation in the readme on how to use it using deps.edn.

Sure I'm happy to help, your parser was very helpful to me last year for a small project I was doing and also right now as I'm trying to migrate all my org notes. I'll start to prepare the PR :-) 

> We are going to expand the transform namespace of org-parser further in order to get a data-structure that's more usable for consuming applications. There might be overlap with your org-parser-tree project - or even synergies to join into one project.

That sounds great, I am also happy to deprecate org-parser-tree as soon as the `transform` namespace is finished so everything related to parsing org files in Clojure is in one project.

**Comment by munen** [comment]
Nice, looking forward to it! Let me know if we can be of help in the meantime^^
